# Generated by Django 4.2.29 on 2026-03-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=6, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('sensitivity', models.CharField(choices=[('strict', 'Strict'), ('balanced', 'Balanced'), ('relaxed', 'Relaxed')], default='balanced', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('desktop_connected', models.BooleanField(default=False)),
                ('mobile_connected', models.BooleanField(default=False)),
                ('desktop_connected_at', models.DateTimeField(blank=True, null=True)),
                ('mobile_connected_at', models.DateTimeField(blank=True, null=True)),
                ('focus_score', models.FloatField(blank=True, null=True)),
                ('focused_minutes', models.FloatField(default=0.0)),
                ('distracted_minutes', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('phone_picked_up', 'Phone Picked Up'), ('phone_put_down', 'Phone Put Down'), ('pwa_backgrounded', 'PWA Backgrounded'), ('pwa_foregrounded', 'PWA Foregrounded'), ('pwa_resumed', 'PWA Resumed'), ('screen_on', 'Screen On'), ('screen_off', 'Screen Off'), ('motion_detected', 'Motion Detected'), ('still', 'Still'), ('heartbeat', 'Heartbeat'), ('session_joined', 'Session Joined'), ('session_left', 'Session Left')], max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_signals', to='core.focussession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FocusScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contributing_signals', models.JSONField(default=dict)),
                ('verdict', models.CharField(choices=[('focused', 'Focused'), ('mild_distraction', 'Mild Distraction'), ('distracted', 'Distracted'), ('phone_use_detected', 'Phone Use Detected'), ('idle_break', 'Idle Break'), ('unknown', 'Unknown')], default='unknown', max_length=25)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='core.focussession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DistractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('distraction_type', models.CharField(choices=[('off_topic_tab', 'Off-Topic Tab'), ('phone_use', 'Phone Use'), ('quick_phone_check', 'Quick Phone Check'), ('inactivity', 'Inactivity'), ('game_detected', 'Game Detected'), ('incognito_window', 'Incognito Window')], max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('score_impact', models.FloatField(default=0.0)),
                ('was_forgiven', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distraction_events', to='core.focussession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DesktopSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('tab_active', 'Tab Active'), ('tab_idle', 'Tab Idle'), ('keystroke_active', 'Keystroke Active'), ('keystroke_idle', 'Keystroke Idle'), ('window_changed', 'Window Changed'), ('intent_study', 'Intent Study'), ('intent_distraction', 'Intent Distraction'), ('presence_detected', 'Presence Detected'), ('presence_absent', 'Presence Absent'), ('heartbeat', 'Heartbeat'), ('session_start', 'Session Start')], max_length=30)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('page_title', models.CharField(blank=True, default='', max_length=512)),
                ('window_title', models.CharField(blank=True, default='', max_length=512)),
                ('topic_relevance_score', models.FloatField(default=0.5)),
                ('timestamp', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_signals', to='core.focussession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
